name: Create a release

on:
  workflow_dispatch:
    inputs:
      version: {required: true}
      pre-id:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jclem/release@release
        with:
          version: ${{ github.event.inputs.version }}
